### ISSUE TITLE
Fails to work on lastest iphone.

### ISSUE THREAD

**Issue by groggu** [leopuleo/easy-panorama#1]
Please update the version of jquery.paver.min.js to fix issues with mobile

**Comment by leopuleo** [comment]
Hi @groggu,
Commit 3bc359c solves this issue.
Thanks very much!

**Comment by HansOtten** [comment]
Works beautiful on a desktop with Chrome, the mouse allows scrolling trough the panorama.

On Android (6) te pano seems to use device orientation to scroll, any touch is ignored. Very odd behaviour results,  mouse touch/wipes on the pano in focus is what users are used to and expect. 

Is this a Paver issue (from what I see the developer os a Iphone user only) or a configuration?
