### ISSUE TITLE
[Feature Request] Vertical Panorama

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [leopuleo/easy-panorama#10]
Would be extremely useful to have the panorama able to pan vertically as well as horizontally.

**Comment by leopuleo** [comment]
Hello @CommunistWitchDoctor,
this feature is similar to the following one, submitted to paver.js, used by Easy Panorama:

https://github.com/terrymun/paver/issues/22

This feature should be implemented in paver.js directly, not by the WordPress plugin itself.
I close the issue and let you know in case of updates.

Thank you,
Leonardo
